API_KEY = "yourapikey"
SECRET_KEY = "yoursecretkey"

SYMBOL = "ETH/USD"
POSITION_SIZE = 0.001

# gridbot settings
NUM_BUY_GRID_LINES = 5
NUM_SELL_GRID_LINES = 5
GRID_SIZE = 2

CHECK_ORDERS_FREQUENCY = 1
CLOSED_ORDER_STATUS = 'closed'
